---
abstract: 'A transparent persistence layer for Tree and its children'
author:
  - 'Rob Kinyon <rkinyon@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-Persist
provides:
  Tree::Persist:
    file: lib/Tree/Persist.pm
    version: 1.08
  Tree::Persist::Base:
    file: lib/Tree/Persist/Base.pm
    version: 1.08
  Tree::Persist::DB:
    file: lib/Tree/Persist/DB.pm
    version: 1.08
  Tree::Persist::DB::SelfReferential:
    file: lib/Tree/Persist/DB/SelfReferential.pm
    version: 1.08
  Tree::Persist::File:
    file: lib/Tree/Persist/File.pm
    version: 1.08
  Tree::Persist::File::XML:
    file: lib/Tree/Persist/File/XML.pm
    version: 1.08
  Tree::Persist::File::XMLWithSingleQuotes:
    file: lib/Tree/Persist/File/XMLWithSingleQuotes.pm
    version: 1.08
requires:
  DBI: 1.627
  File::Slurp: 9999.19
  File::Spec: 0.01
  File::Spec::Functions: 0.01
  File::Temp: 0.01
  Module::Runtime: 0.013
  Scalar::Util: 1.1
  Test::File: 1.1
  Test::File::Contents: 0.02
  Tree: 1.05
  XML::Parser: 2.41
  base: 0
  perl: 5.006000
  strict: 0
  warnings: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.08
